name: Zilosphoto
favicon: null
layout_spectrum: 0.8926233022939414
typography_spectrum: 0.8236556965857744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8816148950718343
  lightness: 0.8353786685038358
  saturation: 0.015260716434568167
  rhythmicContrast: 0.05679092602804303
purpose: []
