name: Zilosphoto
favicon: null
layout_spectrum: 0.76078
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#777f94'
    - '#263646'
    - '#abb2bc'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.05679092602804303
purpose: []
